# Generated by Django 4.2.1 on 2023-05-17 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='customer_id',
        ),
    ]
